<?php

namespace AppBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public $titles = ['mr', 'ms', 'mrs', 'dr', 'mx'];

    public function getTitles()
    {
        return $this->titles;
    }

}
